[package]
name = "test-gen"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
proc-macro2.workspace = true
quote.workspace = true

glob.workspace = true
wast.workspace = true
enumset.workspace = true
