[package]
name = "wasm-gpu"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Runs WASM on the GPU, seamlessly"
homepage = "https://github.com/LucentFlux/wasm-gpu"
repository = "https://github.com/LucentFlux/wasm-gpu"
readme = "README.md"
keywords = ["wasm", "webassembly", "gpu"]
categories = ["compilers", "hardware-support", "wasm", "virtualization"]
include = ["/Cargo.toml", "/LICENSE", "/README.md", "/src/**"]

[dependencies]
wgpu = { version = "0.16", features = ["naga"] }
wgpu-async = { path = "../wgpu-async" }
wgpu-lazybuffers = { path = "../wgpu-lazybuffers" }
wgpu-lazybuffers-operations = { path = "../wgpu-lazybuffers-operations" }
wgpu-lazybuffers-interleaving = { path = "../wgpu-lazybuffers-interleaving" }
wgpu-lazybuffers-macros = { path = "../wgpu-lazybuffers-macros" }
wasm-opcodes = { path = "../wasm-opcodes" }
wasm-types = { path = "../wasm-types" }
wasm-gpu-funcgen = { path = "../wasm-gpu-funcgen" }
lf-gfx = { path = "../lf-gfx" }

thiserror = "1.0"
anyhow = "1.0"
env_logger = "0.10"
cps = "0.2"
itertools = "0.10"
async-trait = "0.1"
elsa = "1.7"
futures = "0.3"
paste = "1.0"
fenwick = "2.0"
ouroboros = "0.15"
perfect-derive = "0.1"
tokio = { version = "1.22", features = ["rt", "rt-multi-thread", "macros"] }
naga = { version = "0.12", features = ["clone"] }
once_cell = "1.17"
pollster = "0.3"

wat = { workspace = true }
wast = { workspace = true }
wasmparser = { workspace = true }
wasmtime-environ = { workspace = true }

[dev-dependencies]
wasm-gpu-test-gen = { path = "test_gen" }
wasm-gpu-test-lib = { path = "test_lib" }
rand = "0.8"

[features]
default = ["big_errors", "opt"] # , "opt"
big_errors = ["wasm-gpu-funcgen/big_errors"]
opt = ["wasm-gpu-funcgen/opt"]