[package]
name = "wasm-spirv"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Transpiles WASM to SPIRV"
homepage = "https://github.com/Solid-Flux/WASM-SPIRV/"
repository = "https://github.com/Solid-Flux/WASM-SPIRV/"
readme = "README.md"
keywords = []
categories = []
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/src/**",
    "/tests/**",
]

[dependencies]
wat = "1.0"
anyhow = "1.0"
wgpu = "0.13"
env_logger = "0.9"
wasmtime = "0.40"
wasmtime-environ = "0.40"
cps = "0.1.0"
itertools = "0.10"
async-trait = "0.1"
elsa = "1.7"
futures = "0.3"
paste = "1.0"

# Tmp dependencies
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
wast = "44.0"
wasm-spirv-test-gen = {path = "test_gen"}
rand = "0.8"