[package]
name = "wasm-spirv"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Transpiles WASM to SPIRV"
homepage = "https://github.com/Solid-Flux/WASM-SPIRV/"
repository = "https://github.com/Solid-Flux/WASM-SPIRV/"
readme = "README.md"
keywords = []
categories = []
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/src/**",
    "/tests/**",
]

[dependencies]
wat = "1.0"
anyhow = "1.0"
wgpu = "0.13"
env_logger = "0.9"
wasmparser = "0.86"
wasmtime = "0.39"
wasmtime-environ = "0.39"
cps = "0.1.0"

[dev-dependencies]
wast = "44.0"
wasm-spirv-test-gen = {path = "test_gen"}