[package]
name = "wasm-gpu-funcgen"
version = "0.1.0"
edition = "2021"


[dependencies]
naga-ext = { path = "../naga-ext" }
wasm-opcodes = { path = "../wasm-opcodes" }
wasm-types = { path = "../wasm-types" }

naga = { version = "0.11", features = ["validate", "hlsl-out", "spv-in", "spv-out"] }
itertools = "0.10"
petgraph = "0.6"
once_cell = "1.17"
thiserror = "1.0"
cps = "0.2"
elsa = "1.7"
paste = "1.0"
perfect-derive = "0.1"
ouroboros = "0.15"
spirv-tools = { version = "0.9", features = [
    "use-compiled-tools",
] }

wasmparser = { workspace = true }
wasmtime-environ = { workspace = true }

[features]
#default = ["opt"]
big_errors = []
opt = []