[package]
name = "wasm-gpu-funcgen"
version = "0.1.0"
edition = "2021"


[dependencies]
wasm-opcodes = { path = "../wasm-opcodes" }
wasm-types = { path = "../wasm-types" }

naga = { version = "0.11", features = ["validate"] }
itertools = "0.10"
wasmparser = "0.93"
petgraph = "0.6"
once_cell = "1.17"
thiserror = "1.0"
cps = "0.2"
wasmtime-environ = "6"
elsa = "1.7"
paste = "1.0"
perfect-derive = "0.1"
ouroboros = "0.15"
