[package]
name = "wasm-spirv"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.14"
wgpu-async = { path = "../wgpu-async" }
wgpu-lazybuffers = { path = "../wgpu-lazybuffers" }
wgpu-lazybuffers-operations = { path = "../wgpu-lazybuffers-operations" }
wgpu-lazybuffers-interleaving = { path = "../wgpu-lazybuffers-interleaving" }
wgpu-lazybuffers-macros = { path = "../wgpu-lazybuffers-macros" }
wasm-opcodes = { path = "../WASM-opcodes" }
wasm-types = { path = "../WASM-types" }
wasm-spirv-funcgen = { path = "../WASM-SPIRV-funcgen" }

wat = "1.0"
thiserror = "1.0"
anyhow = "1.0"
env_logger = "0.9"
wasmparser = "0.93"
cps = "0.2"
itertools = "0.10"
async-trait = "0.1"
elsa = "1.7"
futures = "0.3"
paste = "1.0"
fenwick = "2.0"
ouroboros = "0.15"
perfect-derive = "0.1"
tokio = { version = "1.22", features = ["rt", "rt-multi-thread", "macros"] }
wast = "50.0"
naga = { version = "0.11", features = ["hlsl-out"] }
once_cell = "1.17"

[dev-dependencies]
rand = "0.8"
wasm-spirv-test-gen = { path = "test_gen" }
wasmtime = { version = "1", features = ["wat"] }
pollster = "0.2"

[build]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
