[package]
name = "exe"
version = "0.1.0"
edition = "2021"

[dependencies]
lf-hal = {path="lf-hal"}

wat = "1.0"
thiserror = "1.0"
anyhow = "1.0"
env_logger = "0.9"
wasmparser = "0.93"
cps = "0.2"
itertools = "0.10"
async-trait = "0.1"
elsa = "1.7"
futures = "0.3"
paste = "1.0"
fenwick = "2.0"
ouroboros = "0.15"
perfect-derive = "0.1"
