[package]
name = "wasm-spirv"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Transpiles WASM to SPIRV"
homepage = "https://github.com/Solid-Flux/WASM-SPIRV/"
repository = "https://github.com/Solid-Flux/WASM-SPIRV/"
readme = "README.md"
keywords = []
categories = []
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/src/**",
    "/tests/**",
]

[dependencies]
wasmer = "2.3.0"
wasmer-types = "2.3.0"
wasmer-compiler = "2.3.0"
loupe = "0.1.3"

[dev-dependencies]
wast = "44.0"
wasm-spirv-test-gen = {path = "test_gen"}