[package]
name = "wasm-spirv"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.14"
wgpu-async = { path = "../wgpu-async" }
wgpu-lazybuffers = { path = "../wgpu-lazybuffers" }
wgpu-lazybuffers-operations = { path = "../wgpu-lazybuffers-operations" }
wgpu-lazybuffers-interleaving = { path = "../wgpu-lazybuffers-interleaving" }
wgpu-lazybuffers-macros = { path = "../wgpu-lazybuffers-macros" }

wat = "1.0"
thiserror = "1.0"
anyhow = "1.0"
env_logger = "0.9"
wasmparser = "0.93"
cps = "0.2"
itertools = "0.10"
async-trait = "0.1"
elsa = "1.7"
futures = "0.3"
paste = "1.0"
fenwick = "2.0"
ouroboros = "0.15"
perfect-derive = "0.1"
tokio = { version = "1.22", features = ["rt", "rt-multi-thread", "macros"] }
wast = "50.0"
naga = "0.10"

[dev-dependencies]
rand = "0.8"
wasm-spirv-test-gen = { path = "test_gen" }
