[package]
name = "test-lib"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
wgpu.workspace = true
wgpu-async.workspace = true
wasm-gpu.workspace = true
wasmtime.workspace = true

pollster.workspace = true
once_cell.workspace = true
