[package]
name = "wasm-gpu-test-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2", features = ["full"] }
proc-macro2 = "1"
quote = "1"
glob = "0.3"
wast = "57"
enumset = "1"

[lib]
proc-macro = true
